AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy an Request-driven Web Service based on AWS App Runner.

Resources:
  ServiceAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: build.apprunner.amazonaws.com
        Version: "2012-10-17"
      # Policies:
      #   - PolicyName: 'Publish2SNS'
      #     PolicyDocument:
      #       Version: '2012-10-17'
      #       Statement:
      #         - Effect: 'Allow'
      #           Action: 'sns:Publish'
      #           Resource: 'arn:aws:sns:eu-west-1:487354732760:AWSProton-env-development-cloudformation-yaml-VLFqTZFyzxyWsLy-ping'
  ServiceAccessRoleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: 
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: ServiceAccessRoleDefaultPolicy
      Roles:
        - Ref: ServiceAccessRole
  AppRunnerService:
    Type: "AWS::AppRunner::Service"
    Properties:
      SourceConfiguration:
        # AuthenticationConfiguration:
        #   AccessRoleArn:
        #     Fn::GetAtt:
        #       - ServiceAccessRole
        #       - Arn
        ImageRepository:
          ImageIdentifier: "public.ecr.aws/aws-containers/hello-app-runner:latest"
          ImageConfiguration:
            Port: "8080"
          ImageRepositoryType: "ECR_PUBLIC"
        AutoDeploymentsEnabled: false
      InstanceConfiguration: 
        Cpu: "1024"
        Memory: "2048"
      HealthCheckConfiguration: 
        Protocol: "HTTP"
        Path: "/"
        Interval: 10
        Timeout: 5
        HealthyThreshold: 1
        UnhealthyThreshold: 5
Outputs:
  AppRunnerServiceARN:
    Value:
      Fn::GetAtt:
        - AppRunnerService
        - ServiceArn
  AppRunnerServiceURL:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Fn::GetAtt:
              - AppRunnerService
              - ServiceUrl
