schema:
  format:
    openapi: "3.0.0"
  service_input_type: "ApprunnerServiceInput"

  types:
    ApprunnerServiceInput:
      type: object
      description: "Input properties for the App runner service"
      properties:
        port:
          title: "Port"
          type: number
          description: "The port to route traffic to"
          default: 80
          minimum: 0
          maximum: 65535
        task_size:
          title: "Task size"
          type: string
          description: "The size of the task you want to run"
          enum: ["medium", "large"]
          default: "medium"
        image:
          title: "Image"
          type: string
          description: "The name/url of the container image"
          minLength: 1
          maxLength: 200